// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoCadastro.Data;

namespace ProjetoCadastro.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20230302141802_CriandoTabelaAlunos")]
    partial class CriandoTabelaAlunos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoCadastro.Models.AlunoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nota");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.MatériaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Matéria")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Matéria");

                    b.ToTable("Matérias");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.NotaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Aluno")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Aluno");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.AlunoModel", b =>
                {
                    b.HasOne("ProjetoCadastro.Models.NotaModel", "NotaModel")
                        .WithMany()
                        .HasForeignKey("Nota");

                    b.Navigation("NotaModel");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.MatériaModel", b =>
                {
                    b.HasOne("ProjetoCadastro.Models.AlunoModel", null)
                        .WithMany("Matéria")
                        .HasForeignKey("Matéria");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.NotaModel", b =>
                {
                    b.HasOne("ProjetoCadastro.Models.AlunoModel", "AlunoModel")
                        .WithMany()
                        .HasForeignKey("Aluno");

                    b.HasOne("ProjetoCadastro.Models.MatériaModel", "MatériaModel")
                        .WithMany()
                        .HasForeignKey("Aluno");

                    b.Navigation("AlunoModel");

                    b.Navigation("MatériaModel");
                });

            modelBuilder.Entity("ProjetoCadastro.Models.AlunoModel", b =>
                {
                    b.Navigation("Matéria");
                });
#pragma warning restore 612, 618
        }
    }
}
